# Generated by Django 4.2.9 on 2026-10-03 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50, verbose_name='事件类型')),
                ('aggregate_ref', models.CharField(max_length=100, verbose_name='业务标识')),
                ('idempotency_key', models.CharField(max_length=200, unique=True, verbose_name='幂等键')),
                ('recipient', models.CharField(max_length=200, verbose_name='收件人')),
                ('channel', models.CharField(default='simulated', max_length=20, verbose_name='通知渠道')),
                ('payload', models.JSONField(default=dict, verbose_name='通知内容')),
                ('status', models.CharField(choices=[('pending', '待投递'), ('sending', '投递中'), ('succeeded', '已成功'), ('failed', '待重试'), ('dead', '最终失败')], default='pending', max_length=20, verbose_name='投递状态')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='已尝试次数')),
                ('max_attempts', models.PositiveIntegerField(default=5, verbose_name='最大尝试次数')),
                ('available_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='下次可投递时间')),
                ('claimed_by', models.CharField(blank=True, default='', max_length=100, verbose_name='认领者')),
                ('claimed_at', models.DateTimeField(blank=True, null=True, verbose_name='认领时间')),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='租约到期时间')),
                ('last_error', models.TextField(blank=True, default='', verbose_name='最近错误')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='成功时间')),
                ('dead_at', models.DateTimeField(blank=True, null=True, verbose_name='终败时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '通知投递箱',
                'verbose_name_plural': '通知投递箱',
                'db_table': 'wh_notification_outbox',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['status', 'available_at'], name='idx_outbox_dispatch'), models.Index(fields=['lease_expires_at'], name='idx_outbox_lease')],
            },
        ),
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_no', models.PositiveIntegerField(verbose_name='第几次尝试')),
                ('result', models.CharField(choices=[('success', '成功'), ('retry', '重试'), ('dead', '最终失败')], max_length=20, verbose_name='结果')),
                ('claimed_by', models.CharField(blank=True, default='', max_length=100, verbose_name='执行者')),
                ('detail', models.TextField(blank=True, default='', verbose_name='详情')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('outbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='warehouse.notificationoutbox', verbose_name='投递箱记录')),
            ],
            options={
                'verbose_name': '通知投递记录',
                'verbose_name_plural': '通知投递记录',
                'db_table': 'wh_notification_delivery',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CustodyStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('frozen', '冻结'), ('rejected', '驳回'), ('released', '放行')], max_length=20, verbose_name='状态动作')),
                ('reason', models.TextField(blank=True, verbose_name='事由')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='变更时间')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custody_statuses', to='warehouse.goods', verbose_name='货物')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custody_operations', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '监管状态变更',
                'verbose_name_plural': '监管状态变更',
                'db_table': 'wh_custody_status',
                'ordering': ['-created_at'],
            },
        ),
    ]
