# Generated by Django 4.2.9 on 2026-10-03 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustodyGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='物资名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='物资编码')),
                ('status', models.CharField(choices=[('frozen', '冻结'), ('rejected', '驳回'), ('released', '放行')], default='frozen', max_length=20, verbose_name='监管状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '监管物资',
                'verbose_name_plural': '监管物资',
                'db_table': 'wh_custody_goods',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustodyStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(choices=[('frozen', '冻结'), ('rejected', '驳回'), ('released', '放行')], max_length=20, verbose_name='原状态')),
                ('to_status', models.CharField(choices=[('frozen', '冻结'), ('rejected', '驳回'), ('released', '放行')], max_length=20, verbose_name='新状态')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('idempotency_key', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='幂等键')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '监管物资状态记录',
                'verbose_name_plural': '监管物资状态记录',
                'db_table': 'wh_custody_status_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt', models.PositiveIntegerField(verbose_name='第几次尝试')),
                ('result', models.CharField(choices=[('success', '成功'), ('retry', '重试'), ('dead', '最终失败')], max_length=10, verbose_name='结果')),
                ('lease_owner', models.CharField(blank=True, default='', max_length=64, verbose_name='作业实例')),
                ('success_count', models.PositiveIntegerField(default=0, verbose_name='成功收件人数')),
                ('failed_recipients', models.JSONField(default=list, verbose_name='失败收件人')),
                ('invalid_recipients', models.JSONField(default=list, verbose_name='失效收件人')),
                ('error', models.TextField(blank=True, default='', verbose_name='失败原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '通知投递流水',
                'verbose_name_plural': '通知投递流水',
                'db_table': 'wh_notification_delivery',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='NotificationOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('custody_status_changed', '监管物资状态变化')], max_length=50, verbose_name='事件类型')),
                ('dedup_key', models.CharField(max_length=128, verbose_name='幂等键')),
                ('payload', models.JSONField(default=dict, verbose_name='事件内容')),
                ('recipients', models.JSONField(default=list, verbose_name='收件人标识')),
                ('delivered_recipients', models.JSONField(default=list, verbose_name='已成功收件人')),
                ('status', models.CharField(choices=[('pending', '待投递'), ('processing', '投递中'), ('succeeded', '投递成功'), ('failed', '最终失败')], db_index=True, default='pending', max_length=20, verbose_name='投递状态')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='尝试次数')),
                ('max_attempts', models.PositiveIntegerField(default=5, verbose_name='最大尝试次数')),
                ('available_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='下次可认领时间')),
                ('last_error', models.TextField(blank=True, default='', verbose_name='最近失败原因')),
                ('lease_owner', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='租约持有者')),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='租约到期时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('succeeded_at', models.DateTimeField(blank=True, null=True, verbose_name='成功时间')),
            ],
            options={
                'verbose_name': '通知投递箱',
                'verbose_name_plural': '通知投递箱',
                'db_table': 'wh_notification_outbox',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['status', 'available_at'], name='idx_outbox_claim')],
            },
        ),
        migrations.AddConstraint(
            model_name='notificationoutbox',
            constraint=models.UniqueConstraint(fields=('event_type', 'dedup_key'), name='uniq_outbox_event_dedup'),
        ),
        migrations.AddField(
            model_name='notificationdelivery',
            name='outbox',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='warehouse.notificationoutbox', verbose_name='投递箱记录'),
        ),
        migrations.AddField(
            model_name='custodystatuslog',
            name='custody_goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='warehouse.custodygoods', verbose_name='监管物资'),
        ),
        migrations.AddField(
            model_name='custodystatuslog',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custody_status_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作人'),
        ),
        migrations.AddField(
            model_name='custodygoods',
            name='registered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_custody_goods', to=settings.AUTH_USER_MODEL, verbose_name='登记人'),
        ),
    ]
